Controllers/CrudController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using neilApp.Models;

namespace neilApp.Controllers
{
    [Route("[controller]")]
    [Route("[controller]/[action]")]
    public class CrudController : Controller
    {
        private readonly ILogger<CrudController> _logger;

        private readonly prelimcrudContext _context;

        public CrudController(prelimcrudContext context)
        {
            _context = context;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View(_context.Categories.ToList());
        }


        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(Category ctg)
        {
            _context.Categories.Add(ctg);
            _context.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public IActionResult Update(Category category)
        {
            if(ModelState.IsValid)
            {
                _context.Categories.Update(category);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }
            return View(category);
        }

        public IActionResult Update(int? id)
        {
            if(id == null)
            {
                return RedirectToAction("Index");
            }
            
            var category = _context.Categories.Where(q => q.Id == id).FirstOrDefault();
            return View(category);
        }

        public IActionResult Delete(int id)
        {
            if(id != 0)
            {
                var categoryDelete = _context.Categories.Where(q => q.Id == id).FirstOrDefault();
                _context.Categories.Remove(categoryDelete);
                _context.SaveChanges();

                return RedirectToAction("Index");
            }

           return RedirectToAction("Index");
        }
    }
}

Views/Crud/Create.cshtml
@model neilApp.Models.Category
@{
    ViewData["Title"] = "Create a Category";
}

<html>
    <head>
    </head>
    <body>
            <div class="butIndex">
                @Html.ActionLink("LIST OF CATEGORY", "Index", "Crud")
            </div>
            <div class="formDiv">
                <!--<p>&#8592; Html.ActionLink("LIST OF CATEGORY", "Index", "Crud")</p>-->
                <p><h2>@ViewData["Title"]</h2></p>
            <form method="post">
                <div class="nameDiv">
                    <br>
                    <label class="nameDiv inputNameLabel" asp-for="Name">Category name</label>
                    <p><input placeholder="Input category name" class="nameDiv inputName" required asp-for="Name" /></p>
                </div>
                <div class="submitDiv">
                    <button class="submitDiv subBut" type="submit">Submit</button>
                </div>
            </form>
            </div>
    </body>
</html>

<style>
    *{
        padding: 0;
        margin : 0;
    }

    .formDiv
    {
        display: flex;
        flex-wrap : wrap;
        padding: 10px;
        margin: 10px;
        border: 2px solid white;
        border-radius : 10px;
        max-width: 350px;
        min-width: 150px;

        align-items: center;
        justify-content: center;

        margin : auto;

        background-color: #f8f8f8;
    }

    body
    {
        background: linear-gradient(90deg, #22c1c3, #fdbb2d);
    }

    .nameDiv
    {
        padding: 2px;
        width: 300px;
        border-radius : 10px;
    }

    .inputNameLabel
    {
        font-weight: bold;
    }

    h2
    {
        margin-top: 10px;
    }

    .submitDiv
    {
        padding: 2px;
        border-radius : 10px;
        width: 180px;

        background-color: #00ab66;
        border: none;

        align-items: center;
        justify-content: center;
    }

    .submitDiv:hover
    {
        background-color: #00d680
    }

    .butIndex a
    {
        padding: 7px 12px;
        text-align: center;
        text-decoration: none;
        display: inline-block;

        border: 2px solid black;
        color: white;
    }

    .butIndex a:hover
    {
        color: black;
    }
</style>

Views/Crud/Delete.cshtml
@model neilApp.Models.Category
@{
    ViewData["Title"] = "Delete a Category";
}

<h2>@ViewData["Title"]</h2>

<!-- NOTE : YOU CAN DELETE THIS .CSHTML -->

Views/Crud/Index.cshtml
@model List<neilApp.Models.Category>
<!--List<int> primeNumbers = new List<int>();-->

@{
    ViewData["Title"] = "CATEGORY LIST";
}

<center>
    <h2>@ViewData["Title"]</h2>
</center>

<div class="butCreate">
    @Html.ActionLink("CREATE CATEGORY", "Create", "Crud")
</div>

<body>
    <head>

    </head>
    <body>
        <div class="tableContainer">
            <table class="categoryList" style="border-radius : 10px";>
                <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Actions</th>
                </tr>
    
            @foreach (var item in Model)
            {
                <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>
                <a class="but butUpdate" asp-action="update" asp-route-id="@item.Id">UPDATE</a>
                |
                <a class="but butDelete" asp-action="delete" asp-route-id="@item.Id">DELETE</a>
                </td>
                </tr>
            }
            </table>
        </div>
    </body>
</body>


<style>
    .categoryList th
    {
        padding-top: 12px;
        padding-bottom: 12px;
        text-align: center;
        background-color: #FBBF77;
        color: white;
    }

    .categoryList 
    {
        border-radius : 30px 30px 30px 30px;
        overflow: hidden;
        border-collapse: collapse;

        text-align: center;
        width: 100%;
    }

    .categoryList td, .categoryList th
    {
        border: 1px solid #ddd;
        padding: 8px;
    }

    .categoryList tr:nth-child(even){background-color: #f8f8f8;}
    .categoryList tr:hover {background-color: #ddd;}

    .categoryList tr
    {
        background-color: #f8f8f8;
    }

    body
    {
        background: linear-gradient(90deg, #22c1c3, #fdbb2d);
    }

    *
    {
        padding: 0;
        margin : 0;
    }

    .butUpdate
    {
        width: 100px;
        border-radius : 10px;
        background: #04AA6D;

        color: white;
    }

    .butUpdate:hover
    {
        background-color: #00d680
    }

    .butDelete
    {
        width: 100px;
        border-radius : 10px;
        background: #f32013;
        color : white;
    }

    .butDelete:hover
    {
        background: #FF4433
    }

    .but
    {
        padding: 7px 12px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
    }

    .butCreate a
    {
        padding: 7px 12px;
        text-align: center;
        text-decoration: none;
        display: inline-block;

        border: 2px solid black;
        color: white;
    }

    .butCreate a:hover
    {
        color: black;
    }
</style>

Views/Crud/Update.cshtml
@model neilApp.Models.Category
@{
    ViewData["Title"] = "Category Update";
}

<html>
    <head>
    </head>
    <body>
            <div class="butIndex">
                @Html.ActionLink("LIST OF CATEGORY", "Index", "Crud")
            </div>
            <div class="formDiv">
                <!--<p>&#8592; Html.ActionLink("LIST OF CATEGORY", "Index", "Crud")</p>-->
                <p><h2>@ViewData["Title"]</h2></p>
            <form asp-action="Update">
                <input type="hidden" asp-for="Id"/>
                <div class="nameDiv">
                    <br>
                    <label class="nameDiv inputNameLabel" asp-for="Name">Category name</label>
                    <p><input placeholder="Input category name" class="nameDiv inputName" required asp-for="Name" /></p>
                </div>
                <div class="submitDiv">
                    <button class="submitDiv subBut" type="submit">Submit</button>
                </div>
            </form>
            </div>
    </body>
</html>

<style>
    *{
        padding: 0;
        margin : 0;
    }

    .formDiv
    {
        display: flex;
        flex-wrap : wrap;
        padding: 10px;
        margin: 10px;
        border: 2px solid white;
        border-radius : 10px;
        max-width: 350px;
        min-width: 150px;

        align-items: center;
        justify-content: center;

        margin : auto;

        background-color: #f8f8f8;
    }

    body
    {
        background: linear-gradient(90deg, #22c1c3, #fdbb2d);
    }

    .nameDiv
    {
        padding: 2px;
        width: 300px;
        border-radius : 10px;
    }

    .inputNameLabel
    {
        font-weight: bold;
    }

    h2
    {
        margin-top: 10px;
    }

    .submitDiv
    {
        padding: 2px;
        border-radius : 10px;
        width: 180px;

        background-color: #00ab66;
        border: none;

        align-items: center;
        justify-content: center;
    }

    .submitDiv:hover
    {
        background-color: #00d680
    }

    .butIndex a
    {
        padding: 7px 12px;
        text-align: center;
        text-decoration: none;
        display: inline-block;

        border: 2px solid black;
        color: white;
    }

    .butIndex a:hover
    {
        color: black;
    }
</style>